version: '3.7'

services:
  app:
    build:
      context: ./frontend-VueJs
      dockerfile: Dockerfile
    ports:
      - "5173:80" # Проброс порта 5173 хоста на порт 80 контейнера
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx
    volumes:
      - ./frontend-VueJs/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80" # Проброс порта 80 хоста на порт 80 контейнера nginx
    depends_on:
      - app
    networks:
      - app-network

  backend:
    build: ./backend-JavaSpring
    ports:
      - "8080:8080" # Проброс порта 8080 хоста на порт 8080 контейнера бэкенда
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/soup_database
      SPRING_DATASOURCE_USERNAME: postgres-soup
      SPRING_DATASOURCE_PASSWORD: 12345679
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: soup_database
      POSTGRES_USER: postgres-soup
      POSTGRES_PASSWORD: 12345679
    ports:
      - "5432:5432" # Проброс порта 5432 хоста на порт 5432 контейнера PostgreSQL
    networks:
      - app-network

networks:
  app-network:
    driver: bridge