spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/soup_database
    username: postgres-soup
    password: 12345679
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public