spring:
  datasource:
    url: jdbc:postgresql://c-c9qr7smoul8u919a4qqn.rw.mdb.yandexcloud.net:6432/soup_database
    username: postgres-soup
    password: 12345679
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public

server:
  adress: 51.250.30.170
  port: 8080