name: deploy

on:
    push:
        branches:
            - other-branch

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Deploy Docker
              run: sh ../deploy.sh
              env:
                  OAUTH: ${{ secrets.OAUTH }}
                  REGISTRY_ID: ${{ secrets.REGISTRY_ID }}
